### ISSUE TITLE
Before PyPI submission

### ISSUE THREAD

**Issue by soodoku** [soodoku/get-weather-data#6]
1. Fix dead links in the readme 
2. Better reorganization of non code files:
   http://python-packaging.readthedocs.io/en/latest/non-code-files.html
   Follow python package structure from here:
   http://docs.python-guide.org/en/latest/writing/structure/
3. Provide simple documentation for how to use the package rather than have separate readme files in separate folders? --- Not sure what is better
4. Add unit tests and add to travis.yml
5. Add PyPI downloads and version badges?

**Comment by suriyan** [comment]
done for 1 to 3 and now submission available here :- https://pypi.python.org/pypi/get-weather-data

**Comment by suriyan** [comment]
PyPI badges added to [README.rst](https://github.com/soodoku/get-weather-data/blob/master/get-weather-data/README.rst)

**Comment by suriyan** [comment]
Full documentation will be revised and publish here :- http://get-weather-data.readthedocs.io/en/latest/index.html

**Comment by suriyan** [comment]
#7 unit tests, tox and travis-ci
