### ISSUE TITLE
inventories folder

### ISSUE THREAD

**Issue by Machine855** [soodoku/get-weather-data#9]
I am using the zip2ws to get weather station data of nearest zip codes. As given in the steps on the website (give link) I installed the required python libraries but once I run the zip2ws.py file I get an error. The instructions say that  it is trying to read the inventories folder but does not say where we can find the inventories folder. Could you please elaborate on where I could find more detailed steps on how to get this data.

**Comment by soodoku** [comment]
apologies for not getting to this till now. you raise a useful point about improving our documentation. we will improve it.

current documentation =
"Don't forget the inventories directory that contains the station files and zip csv that is imported. The inventories folder should be in the same folder as the script."

https://github.com/soodoku/get-weather-data/tree/master/zip2ws

in the future, we will add details from zip2ws:

"ASOS_STATIONS_LIST  =   resource_filename(__name__, "inventories/asos-stations.txt")
COOP_STATIONS_LIST  =   resource_filename(__name__, "inventories/coop-act.txt")"
